$(document).ready(function(){
$('.slider').slick({
    arrows:true,
    dots:true,
    adaptiveHeight:true,
    slidesToShow:2,
    slidesToScroll:2,
    infinite:false,
    draggable:false,
    swipe:false,
});
});